const tileIds = {
	sand1: "sand1.png",
	sand2: "sand2.png",
	sand3: "sand3.png",
	grass1: "grass1.png",
	grass2: "grass2.png",
	grass3: "grass3.png",
	water_deep: "water_deep.png",
	water_low: "water_low.png",
	water_sand: "water_sand.png",
	mountain: "mountain.png",
	A: "A.png",
	AttackB: "AttackB.png",
	D: "D.png",
	DigB: "DigB.png",
	S: "S.png",
	W: "W.png",
}